### ISSUE TITLE
Lock dependency of `bramus/router` to prevent future breaking

### ISSUE THREAD

**Issue by bramus** [groucho75/phmisk#1]
As the author of [`bramus/router`](https://github.com/bramus/router) I'm glad to see that you're using my router in your project :-)

However, when checking the contents of your `package.json`, I see that you're referring to `dev-master` as the version. To prevent your code from breaking in the future, I recommend you to lock to a specific version.

Version 1.4 is the current release. It can be included by executing `composer require bramus/router ~1.4`.

**Comment by groucho75** [comment]
I've update the composer.json with `bramus/router ~1.4`. Thank you very much
